# Generated by Django 2.1.2 on 2018-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181109_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
