# Generated by Django 2.1.2 on 2018-11-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_friendshiprequest'),
        ('posts', '0003_post_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='main.CustomUser'),
        ),
    ]
