version: '3'

services: 
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'my-app-user'
       MYSQL_PASSWORD: '123456'
       MYSQL_ROOT_PASSWORD: '123456' 
  web:
    image: socialnetwork-img:latest
    volumes:
      - .:/app
    restart: always    
    ports:
      - '8000:8000'
    depends_on:
      - db