# Generated by Django 2.1.2 on 2018-10-26 21:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img_profile',
            field=models.ImageField(default='avatar2.png', upload_to=main.models.user_directory_path),
        ),
    ]
